Publish Lorenz Meyer's interview
PrestaShop/prestashop.github.io pull request #1034
Opened 2022-02-02 13:29 UTC by Julievrz

I'd like it to be published on February 10 if possible. Thanks!

2022-02-02 13:44 UTC, okom3pom requested changes

2022-02-02 13:44 UTC, okom3pom commented on news/_posts/2022-02-09-contributor-interview-lorenz-meyer.md
> +<img style="border: 1px solid #CCC; float: left; margin: 0 1em 1em 0;" width="180" height="240" src="/assets/images/2022/02/lorenz-meyer.jng">
```suggestion
<img style="border: 1px solid #CCC; float: left; margin: 0 1em 1em 0;" width="180" height="240" src="/assets/images/2022/02/lorenz-meyer.png">
```

2022-02-02 13:45 UTC, okom3pom commented on news/_posts/2022-02-09-contributor-interview-lorenz-meyer.md
> +<img style="border: 1px solid #CCC; float: left; margin: 0 1em 1em 0;" width="180" height="240" src="/assets/images/2022/02/lorenz-meyer.jng">
```suggestion
<img style="border: 1px solid #CCC; float: left; margin: 0 1em 1em 0;" width="180" height="240" src="/assets/images/2022/02/lorenz-meyer.jpg">
```

2022-02-02 13:52 UTC, Julievrz commented on news/_posts/2022-02-09-contributor-interview-lorenz-meyer.md
> +<img style="border: 1px solid #CCC; float: left; margin: 0 1em 1em 0;" width="180" height="240" src="/assets/images/2022/02/lorenz-meyer.jng">
Nice catch, thanks!

2022-02-03 09:38 UTC, atomiix approved these changes

2022-02-03 10:07 UTC, MatShir commented on news/_posts/2022-02-09-contributor-interview-lorenz-meyer.md
> +Have you ever wondered who was hiding behind a GitHub username? It’s time to find out! Contributor interviews are a great way of getting to know the people who participate in the PrestaShop project.
```suggestion
Have you ever wondered who was hiding behind a GitHub username? It’s time to find out! Contributor interviews are a great way of getting to know the people who participate in the PrestaShop project. This month, meet Lorenz Meyer aka [@lmeyer1](https://github.com/lmeyer1).
```
A suggestion :)

2022-02-03 10:21 UTC, saulaski approved these changes

2022-02-03 11:19 UTC, Julievrz commented on news/_posts/2022-02-09-contributor-interview-lorenz-meyer.md
> +Have you ever wondered who was hiding behind a GitHub username? It’s time to find out! Contributor interviews are a great way of getting to know the people who participate in the PrestaShop project.
Yep, good idea, thanks. I hesitated because I was afraid it'd be too informal, but the tone on Build is not that formal after all. :-)

2022-02-09 08:56 UTC, NeOMakinG approved these changes

2022-02-10 08:40 UTC, merged

2022-02-10 08:40 UTC, atomiix commented
Thanks @Julievrz!