Upcoming demo 7/2022
PrestaShop/prestashop.github.io pull request #1131
Opened 2022-09-29 12:45 UTC by kpodemski

October's public demo announcement.

2022-09-29 13:11 UTC, matthieu-rolland approved these changes

2022-09-30 08:21 UTC, coffrep requested changes

2022-09-30 08:21 UTC, coffrep commented on news/_posts/public-oss-demo/2022-09-29-upcoming-demo-7-2022.md
> +**If you have any questions about things related to the open source project** feel free to ask [using this form](https://forms.gle/FWazuZnXBtFPauFZ7). We will answer them during Q&A session.
```suggestion
**If you have any questions about things related to the open source project** feel free to ask [using this form](https://forms.gle/FWazuZnXBtFPauFZ7). We will answer them during the Q&A session.
```

2022-09-30 08:21 UTC, coffrep commented on news/_posts/public-oss-demo/2022-09-29-upcoming-demo-7-2022.md
> +The session will be kept in record on YouTube, so that even if you can't attend to the live stream, you will still be able to catch up later.
```suggestion
The session will be kept in record on YouTube, so even if you can't attend the live stream, you will still be able to catch up later.
```

2022-09-30 08:21 UTC, coffrep commented on news/_posts/public-oss-demo/2022-09-29-upcoming-demo-7-2022.md
> +- Update from PrestaShop 1.7.8 to 8.0 using [autoupgrade](https://github.com/PrestaShop/autoupgrade) module [@kpodemski](https://github.com/kpodemski)
```suggestion
- Update from PrestaShop 1.7.8 to 8.0 using [autoupgrade](https://github.com/PrestaShop/autoupgrade) module, by [@kpodemski](https://github.com/kpodemski)
```

2022-09-30 08:33 UTC, coffrep approved these changes

2022-09-30 08:33 UTC, merged