Create do-you-speak-prestashop-january-2023.md
PrestaShop/prestashop.github.io pull request #1191
Opened 2023-02-02 13:13 UTC by l-delin

2023-02-02 13:21 UTC, l-delin commented
ping @coffrep

2023-02-02 14:22 UTC, coffrep requested changes
Quelques suggestions - j'ai juste suggéré de modifier le mois à quelques reprises, je ne sais pas si ca a du sens pour toi ?

2023-02-02 14:22 UTC, coffrep commented on content/news/translation/2023/do-you-speak-prestashop-january-2023.md
> +Contributing to PrestaShop is not only about the code, it is also about taking part in the [PrestaShop translation project](https://crowdin.com/project/prestashop-official)! This report will tell you
```suggestion
Contributing to PrestaShop is not only about the code, it is also about taking part in the [PrestaShop translation project](https://crowdin.com/project/prestashop-official)! This report will tell you how the software translations evolved in January!
```

2023-02-02 14:22 UTC, coffrep commented on content/news/translation/2023/do-you-speak-prestashop-january-2023.md
> +Ever wondered how the translation process works? or how to become a proofreader? The translation guide is there to help. You can find it [here](https://docs.prestashop-project.org/translating-prestas
```suggestion
Ever wondered how the translation process works? Or how to become a proofreader? The translation guide is there to help. You can find it [here](https://docs.prestashop-project.org/translating-prestashop/).
```

2023-02-02 14:22 UTC, coffrep commented on content/news/translation/2023/do-you-speak-prestashop-january-2023.md
> +At the end of December, PrestaShop 8 was fully available (= 100% translated and validated) in **14 languages**. That’s great!
```suggestion
At the end of January, PrestaShop 8 was fully available (= 100% translated and validated) in **14 languages**. That’s great!
```

2023-02-02 14:22 UTC, coffrep commented on content/news/translation/2023/do-you-speak-prestashop-january-2023.md
> + Thank you for your involvement. :tada:
```suggestion
 Thank you for your involvement. :tada:
 
```

2023-02-02 14:22 UTC, coffrep commented on content/news/translation/2023/do-you-speak-prestashop-january-2023.md
> +The following languages had the best progress in December thanks to the translation community:
```suggestion
The following languages had the best progress in January thanks to the translation community:
```

2023-02-02 14:47 UTC, coffrep approved these changes
Thanks for the great post! As mentioned on Slack, super if this post is published beginning of next week - thanks Léa.

2023-02-06 16:10 UTC, kpodemski commented on content/news/translation/2023/do-you-speak-prestashop-january-2023.md
> +date: 2023-03-02
```suggestion
date: 2023-02-07
`

:)

2023-02-06 16:45 UTC, coffrep commented on content/news/translation/2023/do-you-speak-prestashop-january-2023.md
> +date: 2023-03-02
Perfect 👍

2023-02-13 08:28 UTC, l-delin commented
Hello, could we get this published? Thank you :-)

2023-02-13 09:29 UTC, kpodemski approved these changes

2023-02-13 09:29 UTC, merged

2023-02-13 09:29 UTC, kpodemski commented
Thanks @l-delin