[wip] Release notes for PrestaShop 8.0.2
PrestaShop/prestashop.github.io pull request #1196
Opened 2023-02-28 20:36 UTC by kpodemski

Release notes for PrestaShop 8.0.2

2023-03-01 13:22 UTC, MatShir requested changes

2023-03-01 13:22 UTC, MatShir commented on content/news/releases/prestashop-8-0-2-maintenance-release.md
> +### Webservoces
```suggestion
### Webservices
```

2023-03-01 13:22 UTC, MatShir commented on content/news/releases/prestashop-8-0-2-maintenance-release.md
> +- [Guest were detected as logged user](https://github.com/PrestaShop/PrestaShop/issues/30991)
```suggestion
- [Guests were detected as a logged-in user](https://github.com/PrestaShop/PrestaShop/issues/30991)
```

2023-03-01 17:32 UTC, MatShir approved these changes

2023-03-01 17:37 UTC, coffrep submitted a review, later dismissed
Just a few suggestions

2023-03-01 17:37 UTC, coffrep commented on content/news/releases/prestashop-8-0-2-maintenance-release.md
> +There were several noteworthy issues addressed in the milestone 8.0.2 of PrestaShop. The upgrade mechanism had a problem where it couldn't check if the PHP session had started on some webservers, whi
```suggestion
There were several noteworthy issues addressed in PrestaShop's 8.0.2 milestone. The upgrade mechanism had a problem where it couldn't check if the PHP session had started on some webservers, which was reported by many community members. Additionally, significant problems with web services were resolved, including the inability to create new customers. Another noteworthy fix was made for enabling themes that use Symfony routes for their modules, which was reported by a community member. Finally, there were several under-the-hood fixes and a new version of [Distribution API client](https://github.com/PrestaShop/ps_distributionapiclient/releases/tag/v1.0.3) released to enhance the module upgrade process.
```

2023-03-01 17:37 UTC, coffrep commented on content/news/releases/prestashop-8-0-2-maintenance-release.md
> +- [With the 1-Click Upgrade module v4.15.0, It was not possible to create a PHP session and no new version was available](https://github.com/PrestaShop/PrestaShop/issues/30658)
```suggestion
- [With the 1-Click Upgrade module v4.15.0, it was not possible to create a PHP session and no new version was available](https://github.com/PrestaShop/PrestaShop/issues/30658)
```

2023-03-01 17:37 UTC, coffrep commented on content/news/releases/prestashop-8-0-2-maintenance-release.md
> +Alexandre Hellin, Boubker Bribri, Daniel Hlavacek, Ibrahima Sow, Krystian Podemski, Léa Delin, Mathieu Ferment, Matthieu Rolland, Maxime Flasquin, Nesrine Abdmouleh, Nicolas Lœuillet, Thomas Baccelli
```suggestion
Alexandre Hellin, Boubker Bribri, Daniel Hlavacek, Ibrahima Sow, Krystian Podemski, Léa Delin, Mathieu Ferment, Matthieu Rolland, Maxime Flasquin, Nesrine Abdmouleh, Nicolas Lœuillet, Thomas Baccelli.
```

2023-03-01 17:37 UTC, coffrep commented on content/news/releases/prestashop-8-0-2-maintenance-release.md
> +It is recommended to upgrade your shop quickly in order to benefit from these fixes. Of course, don’t forget to backup before. You can upgrade to the latest version using 1-Click Upgrade [v4.15.0](ht
```suggestion
It is recommended to upgrade your shop quickly in order to benefit from these fixes. Of course, don’t forget to backup before. You can upgrade to the latest version using the 1-Click Upgrade [v4.15.0](https://github.com/PrestaShop/autoupgrade/releases/tag/v4.15.0).
```

2023-03-03 15:36 UTC, coffrep approved these changes

2023-03-13 17:01 UTC, merged