Create contributor-interview-amirhossein.md
PrestaShop/prestashop.github.io pull request #1203
Opened 2023-03-29 13:00 UTC by l-delin

2023-03-29 13:09 UTC, Julievrz commented on content/news/posts/2023/contributor-interview-amirhossein.md
> +<img style="border: 1px solid #CCC; float: center; margin: 0 1em 1em 0;" width="517" height="388" src="/assets/images/2023/03/amirhossein.png">
```suggestion
<img style="border: 1px solid #CCC; float: center; margin: 0 1em 1em 0;" width="517" height="388" src="static/assets/images/2023/03/amirhossein.png">
```

2023-03-29 13:10 UTC, Julievrz commented on content/news/posts/2023/contributor-interview-amirhossein.md
> +image: /assets/images/2023/03/amirhossein.png
```suggestion
image: static/assets/images/2023/03/amirhossein.png
```

2023-03-29 13:24 UTC, l-delin commented
Contributor interviews are back 🎉🐧  Thanks @Julievrz 

Ping @coffrep for review

2023-03-29 13:30 UTC, l-delin commented
Hello @PrestaShop/prestashop-maintainers, could any of you check and tell me if the picture is working? When I click on it, it redirects to the wrong repo but  I know the picture is in the exact folder I specified, same branch, everything:

![image](https://user-images.githubusercontent.com/113511191/228553363-58962aa0-e24f-410b-aa03-4ee5a336b3fb.png)

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/113511191/228553651-479f983a-ef05-4b92-a5c8-c7ec487b29e0.png">

2023-03-29 14:06 UTC, coffrep requested changes
Hi l-delin, I've added very minor suggestions, trying to keep the interview as original as possible in the member's own tone.

2023-03-29 14:06 UTC, coffrep commented on content/news/posts/2023/contributor-interview-amirhossein.md
> +Fasleaval, on the other hand, is an agency specializing in PrestaShop products and services. We have provided tens of hours of [free training videos](https://fasleaval.com/blog/آموزش-پرستاشاپ-رایگان-
```suggestion
Fasleaval, on the other hand, is an agency specializing in PrestaShop products and services. We have provided tens of hours of [free training videos](https://fasleaval.com/blog/آموزش-پرستاشاپ-رایگان-ویدیوی) from downloading PrestaShop up to some more advanced configurations. We also offer some themes and modules.
```

2023-03-29 14:06 UTC, coffrep commented on content/news/posts/2023/contributor-interview-amirhossein.md
> +I have also helped to teach PrestaShop in high schools in Iran. There’s one chapter in textbooks dedicated to PrestaShop and tens of thousands of students learn to use PrestaShop every year since 201
```suggestion
I have also helped to teach PrestaShop in high schools in Iran. There’s one chapter in textbooks dedicated to PrestaShop and tens of thousands of students learn how to use PrestaShop every year since 2018.
```

2023-03-29 14:06 UTC, coffrep commented on content/news/posts/2023/contributor-interview-amirhossein.md
> +And that’s how, less than a year later, Fasleaval was founded. We started uploading free PrestaShop training videos and I guess many people have used those videos so far to start their own e-commerce
```suggestion
And that’s how, less than a year later, Fasleaval was founded. We started uploading free PrestaShop training videos and I guess many people have used those videos so far to start their own ecommerce by PrestaShop.
```

2023-03-29 14:13 UTC, l-delin commented
Thank you @coffrep :-) I'm waiting for feedback regarding the picture in the article and once that's been fixed, I think the article will be ready to go

2023-04-11 14:30 UTC, l-delin commented
Hello @coffrep, could we get this article published this week or the next one? :-) 
I'll submit the Crowdin Monthly later this week, it would be nice if the monthly's were published this week (it'll be posted a bit late otherwise)

2023-04-11 14:37 UTC, coffrep commented
Hi @l-delin, great news! Yes we can publish this contributor interview either this week or next week. Please do submit it when it is good for you.

2023-04-11 15:07 UTC, l-delin commented
Hi, that's perfect. Can it be published tomorrow, on 04/12? That way I can talk about the interview on the next Crowdin Monthly. Thank you!

2023-04-12 10:00 UTC, coffrep approved these changes

2023-04-12 12:29 UTC, l-delin commented
Hello, could I please get a merge @kpodemski ? :-) Thank you!

2023-04-12 16:07 UTC, kpodemski approved these changes

2023-04-12 16:07 UTC, merged

2023-04-12 16:07 UTC, kpodemski commented
thanks @l-delin @coffrep :)