Create prestashop-81-translations.md
PrestaShop/prestashop.github.io pull request #1217
Opened 2023-05-11 09:25 UTC by l-delin

on standby until the 8.1 catalog is pushed

2023-05-11 13:19 UTC, l-delin commented
The catalog has been pushed so this announcement is ready to be published 🥳  @coffrep @kpodemski

2023-05-11 15:49 UTC, coffrep requested changes
Hi @l-delin, great post, I'm just adding a few suggestions.

2023-05-11 15:49 UTC, coffrep commented on content/news/posts/2023/prestashop-81-translations.md
> +### New strings & completion rates
```suggestion
### New strings and completion rates 
```

2023-05-11 15:49 UTC, coffrep commented on content/news/posts/2023/prestashop-81-translations.md
> +### New strings & completion rates
```suggestion
### New strings and completion rates 
```

2023-05-11 15:49 UTC, coffrep commented on content/news/posts/2023/prestashop-81-translations.md
> +### A note on variables & QA checker
```suggestion
### A note on variables and QA checker
```

2023-05-11 15:49 UTC, coffrep commented on content/news/posts/2023/prestashop-81-translations.md
> +Note that the QA checker will be enabled in the project in the upcoming weeks. Variables will then be automatically checked in target translations to make sure no variables slip through the cracks an
```suggestion
Note that the QA checker will be enabled in the project in the upcoming weeks. Variables will then be automatically checked in target translations to make sure no variables slip through the cracks anymore. If you wish to know more about these changes, keep an eye out for the next Crowdin Monthly, or check out the PrestaShop Open Source project's Slack translation channel.
```

2023-05-12 14:45 UTC, l-delin commented
Thank you @coffrep ! I've added a section on QA checks since we enabled them on Crowdin right after the release of the catalog. Let me know what you think 😊

2023-05-12 14:59 UTC, tleon approved these changes

2023-05-12 15:34 UTC, coffrep approved these changes
Hi @l-delin, I'm approving with one change.

2023-05-12 15:34 UTC, coffrep commented on content/news/posts/2023/prestashop-81-translations.md
> +If you wish to learn more about the QA checker and how it works, can check out the [Crowdin documentation](https://support.crowdin.com/qa-checks/).
```suggestion
If you wish to learn more about the QA checker and how it works, you can check out the [Crowdin documentation](https://support.crowdin.com/qa-checks/).
```

2023-05-12 15:34 UTC, coffrep commented on content/news/posts/2023/prestashop-81-translations.md
> +If you wish to learn more about the QA checker and how it works, can check out the [Crowdin documentation](https://support.crowdin.com/qa-checks/).
```suggestion
If you wish to learn more about the QA checker and how it works, you can check out the [Crowdin documentation](https://support.crowdin.com/qa-checks/).
```

2023-05-12 15:37 UTC, l-delin commented
Done 👋

2023-05-16 12:04 UTC, merged

2023-05-16 12:04 UTC, kpodemski commented
thanks @l-delin :)