Create contributor-interview-louis-authie.md
PrestaShop/prestashop.github.io pull request #1219
Opened 2023-05-11 09:44 UTC by l-delin

2023-05-11 09:45 UTC, l-delin commented
ping @coffrep and @kpodemski for review :-)

2023-05-11 13:35 UTC, coffrep requested changes
Hi @l-delin, great interview of Louis, added a few suggestions and a comment about his book link. Let me know of your thoughts.

2023-05-11 13:35 UTC, coffrep commented on content/news/posts/2023/contributor-interview-louis-authie.md
> +**Louis is a freelance full stack developer at Web Helpers, with over 120 contributions on GitHub. He’s also a member of [Friends of Presta](https://friendsofpresta.org/en), an association that gathe
```suggestion
**Louis is a freelance full stack developer at Web Helpers, with over 120 contributions on GitHub. He’s also a member of [Friends of Presta](https://friendsofpresta.org/en), an association that gathers a community of developers and integrators around the open source ecommerce solution PrestaShop.**
```

2023-05-11 13:35 UTC, coffrep commented on content/news/posts/2023/contributor-interview-louis-authie.md
> +I installed PrestaShop for the first time back in 2012, (I can’t recall if it was 1.2 or 1.5!), but it was very different, and anyone could understand PHP. Then again, it was much simpler back then,
```suggestion
I installed PrestaShop for the first time back in 2012 (I can’t recall if it was 1.2 or 1.5!), but it was very different, and anyone could understand PHP. Then again, it was much simpler back then, even though I was a noob. 😄
```

2023-05-11 13:35 UTC, coffrep commented on content/news/posts/2023/contributor-interview-louis-authie.md
> +If you buy the book on Amazon and use the voucher **20LOUIS**, you get 20% off, here: https://www.amazon.com/gp/mpc/A1C6DNDDRD3ZU5. The voucher’s active until May 31st.
I was questioning whether it was a good thing to add a link to his book on this interview. But, the fact he is promoting a book where revenue goes to a non-profit like FOP - not in his pocket - feels like it's okay to add his link.

2023-05-11 13:35 UTC, coffrep commented on content/news/posts/2023/contributor-interview-louis-authie.md
> +If you buy the book on Amazon and use the voucher **20LOUIS**, you get 20% off, here: https://www.amazon.com/gp/mpc/A1C6DNDDRD3ZU5. The voucher’s active until May 31st.
```suggestion
If you buy the book on Amazon and use the voucher **20LOUIS**, [you get 20% off, here](https://a.co/d/eOsfniP). The voucher’s active until May 31st.
```

2023-05-11 13:59 UTC, l-delin commented
Thank you @coffrep! I added all your edits. Edited the URL too because it wasn't working

2023-05-11 14:52 UTC, boherm commented on content/news/posts/2023/contributor-interview-louis-authie.md
> +**Do you wish to contribute to the PrestaShop Project? Everything you need to know is available [here]([https://docs.prestashop-project.org/v.8-documentation/v/english]). You can join us on the Prest
Just a little typo here! 😊

```suggestion
**Do you wish to contribute to the PrestaShop Project? Everything you need to know is available [here]([https://docs.prestashop-project.org/v.8-documentation/v/english]). You can join us on the PrestaShop Project, available on [GitHub]([https://github.com/PrestaShop).**
```

2023-05-11 15:39 UTC, coffrep approved these changes
Great, thanks @l-delin, good on my end!

2023-05-12 08:44 UTC, nicosomb requested changes

2023-05-12 08:44 UTC, nicosomb commented on content/news/posts/2023/contributor-interview-louis-authie.md
> +<img style="border: 1px solid #CCC; float: center; margin: 0 1em 1em 0;" width="517" height="388" src="/assets/images/2023/05/lauthie.jpg">
Picture is missing.

2023-05-12 08:47 UTC, boherm commented on content/news/posts/2023/contributor-interview-louis-authie.md
> +<img style="border: 1px solid #CCC; float: center; margin: 0 1em 1em 0;" width="517" height="388" src="/assets/images/2023/05/lauthie.jpg">
It seems to be in another PR (https://github.com/PrestaShop/prestashop.github.io/pull/1218), but yes this image could be in this PR instead of another one.

2023-05-12 10:53 UTC, kpodemski approved these changes

2023-05-12 10:54 UTC, merged