PrestaShop 8.1 RC 1 release notes
PrestaShop/prestashop.github.io pull request #1223
Opened 2023-05-23 13:09 UTC by kpodemski

RN for 8.1 RC 1

2023-05-24 07:37 UTC, matks reviewed
Two little suggestions ;)

As for "June X" I bring you the date ASAP

2023-05-24 07:37 UTC, matks commented on content/news/releases/prestashop-8-1-rc1-release.md
> +All the critical bugs have been fixed, and [the remaining ones](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aopen+is%3Aissue+label%3A8.1.x+label%3ABug+label%3ARegression) will be fixed in t
```suggestion
All the critical bugs have been fixed, and [the remaining ones](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aopen+is%3Aissue+label%3A8.1.x+label%3ABug+label%3ARegression) will be fixed in the upcoming 8.1.x patch release.
```

Depending on number of bugs, it could take more than 1 patch to fix them all. Also if a vulnerability is reported we might have to release earlier than expected PS 8.1.1 (like 2 weeks instead of 6) preventing us to fulfill this promise.

2023-05-24 07:37 UTC, matks commented on content/news/releases/prestashop-8-1-rc1-release.md
> +0x346e3730, Alexandre Hellin, Antonin Clauzier, bibips, Boris Hermans, Boubker Bribri, Cedric Vangout, Codencode, Daniel Hlavacek, Fabien Papet, Franck Lefèvre, Ibrahima Sow, Jakub Łach, Jens Wilke,
```suggestion
Alexandre Hellin, Antonin Clauzier, bibips, Boris Hermans, Boubker Bribri, Cedric Vangout, Codencode, Daniel Hlavacek, Fabien Papet, Franck Lefèvre, Ibrahima Sow, Jakub Łach, Jens Wilke, jevgenijvisockij, Jonathan Lelievre, Julius Žukauskas, Krystian Podemski, Léa Delin, Lorenz Meyer, Mathias Reker, Mathieu Ferment, Matthieu Rolland, Maxime Flasquin, Nesrine Abdmouleh, Nicolas Lœuillet, Pablo Borowicz, PICHAT Morgan, Prestaworks, PrestonBot, Robin Fischer, Salim Benouamer, Sharak, Thomas Baccelli, Thomas Nares, Thomas Leone
```
My bad, I just saw that there is a duplicate: Antonin Clauzier is 0x346e3730

2023-05-24 20:32 UTC, matks reviewed
Publish date: 25th of May
Finale release date (I hope): 26th of June

2023-05-24 20:32 UTC, matks commented on content/news/releases/prestashop-8-1-rc1-release.md
> +date: 2023-05-23
```suggestion
date: 2023-05-25
```

2023-05-24 20:32 UTC, matks commented on content/news/releases/prestashop-8-1-rc1-release.md
> +We're on the brink of releasing the final 8.1 version. This time, the Release Candidate version is being shared simultaneously with the community and the project's Quality Assurance (QA) team. The id
```suggestion
We're on the brink of releasing the final 8.1 version. This time, the Release Candidate version is being shared simultaneously with the community and the project's Quality Assurance (QA) team. The idea is for everyone to collectively confirm that all issues identified in the beta version have been resolved, ensuring their suitability for production use. If no major problems are reported by June 26th, we'll move ahead and launch the final version of 8.1.
```

2023-05-24 20:32 UTC, matks commented on content/news/releases/prestashop-8-1-rc1-release.md
> +**Please submit all your feedback by June X, 2023.** If no new critical or major issue remains to be fixed by then, the final release will be made available. This is the final chance to test this new
```suggestion
**Please submit all your feedback by June 26th, 2023.** If no new critical or major issue remains to be fixed by then, the final release will be made available. This is the final chance to test this new version before the final release is out!
```

2023-05-25 08:51 UTC, matks approved these changes
Approval for publishing A S A P 🎉

2023-05-25 09:38 UTC, coffrep requested changes
Great post well written @kpodemski - just 2 suggestions on the RC term and upper casing.

2023-05-25 09:38 UTC, coffrep commented on content/news/releases/prestashop-8-1-rc1-release.md
> +![PrestaShop 8.1 Release Candidate 1 is available](/assets/images/2023/02/banner_8.1_1534x424.png)
```suggestion
![PrestaShop 8.1 release candidate 1 is available](/assets/images/2023/02/banner_8.1_1534x424.png)
```

2023-05-25 09:38 UTC, coffrep commented on content/news/releases/prestashop-8-1-rc1-release.md
> +We're on the brink of releasing the final 8.1 version. This time, the Release Candidate version is being shared simultaneously with the community and the project's Quality Assurance (QA) team. The id
```suggestion
We're on the brink of releasing the final 8.1 version. This time, the release candidate version is being shared simultaneously with the community and the project's Quality Assurance (QA) team. The idea is for everyone to collectively confirm that all issues identified in the beta version have been resolved, ensuring their suitability for production use. If no major problems are reported by June 26th, we'll move ahead and launch the final version of 8.1.
```

2023-05-25 09:45 UTC, coffrep approved these changes

2023-05-25 09:46 UTC, merged