[wip] Release notes for PrestaShop 8.1
PrestaShop/prestashop.github.io pull request #1232
Opened 2023-06-20 14:02 UTC by kpodemski

8.1 is coming!

2023-06-20 14:19 UTC, Robin-Fischer-PS reviewed
Added the QA members in suggested change, otherwise looks good, thanks :)

2023-06-20 14:19 UTC, Robin-Fischer-PS commented on content/news/releases/prestashop-8-1-0-available.md
> +- Quality assurance: Aurélien Rita, Faten Mhiri, Florine Hea, Hana Rebai, Hibatallah Aouadni, Ines Sallemi, Khouloud Belguith, Marwa Chelly, Paul-Noël Cholot, Robin Fischer, Sarah Cavrot, Sarah Dib,
```suggestion
- Quality assurance: Achraf Kchaou, Anis Zouari, Aurélien Rita, Emna Chouichi, Faten Mhiri, Florine Hea, Hana Rebai, Hejer Elleuch, Hibatallah Aouadni, Ines Sallemi, Khouloud Belguith, Paul-Noël Cholot, Robin Fischer, Sarah Dib and Serhii Zavadskyi.
```

2023-06-22 10:04 UTC, coffrep commented on content/news/releases/prestashop-8-1-0-available.md
> +date: 2023-06-20
Date to modify before publishing

2023-06-22 10:18 UTC, coffrep requested changes, later dismissed
Hi Krystian, great article for 8.1! I'm requesting changes on this file. It would be great if you could let me re-read the article once every edit has been made (adding contributors, numbers, etc...).

2023-06-22 10:18 UTC, coffrep commented on content/news/releases/prestashop-8-1-0-available.md
> +PrestaShop 8.1, is a minor upgrade with major improvements. It's focused on making things faster and easier for you, transforming the way you use PrestaShop.
```suggestion
PrestaShop 8.1 is a minor upgrade with major improvements. It's focused on making things faster and easier for you, transforming the way you use PrestaShop.
```

2023-06-22 10:18 UTC, coffrep commented on content/news/releases/prestashop-8-1-0-available.md
> +The entirely reworked product management page delivers a more efficient and user-friendly experience. This new page make managing product combinations, prices, taxes, stock, and images quicker and ea
```suggestion
The entirely reworked product management page delivers a more efficient and user-friendly experience. This new page makes managing product combinations, prices, taxes, stock, and images quicker and easier. Multistore product management has also been drastically improved. Performance-wise, the new product management page is taken to a new level, especially for stores with a large number of combinations.
```

2023-06-22 10:18 UTC, coffrep commented on content/news/releases/prestashop-8-1-0-available.md
> +Additional new features include improved control over product availability labels, enhanced SEO settings for products, and support for multiple format image generation (WebP, AVIF). There are also a
```suggestion
Additional new features include improved control over product availability labels, enhanced SEO settings for products, and support for multiple format image generation (WebP, AVIF). There are also a few improvements for developers, such as simplified access to the store's performance profiler.
```

2023-06-22 10:18 UTC, coffrep commented on content/news/releases/prestashop-8-1-0-available.md
> +- Product management: Fabien Vallon, Mateus Shirlaw, Zoé Finders and Rosa Benouamer
```suggestion
- Product management: Fabien Vallon, Mateus Shirlaw, Zoé Finders and Rosa Benouamer.
```

2023-06-26 14:56 UTC, merged