Update for outdated articles
PrestaShop/prestashop.github.io pull request #1238
Opened 2023-07-10 09:07 UTC by kpodemski

Work in progress.

2023-08-14 15:40 UTC, eternoendless commented on content/howtos/module/2015-05-09-how-to-override-modules.md
> +{{% notice type="danger" title="This article may be outdated" icon="megpahone" %}}
Isn't it megaphone?
```suggestion
{{% notice type="danger" title="This article may be outdated" icon="megaphone" %}}
```

2023-08-17 08:18 UTC, kpodemski commented on content/howtos/module/2015-05-09-how-to-override-modules.md
> +{{% notice type="danger" title="This article may be outdated" icon="megpahone" %}}
indeed, it is :)

2023-09-19 11:38 UTC, eternoendless requested changes

2023-09-19 11:38 UTC, eternoendless commented on content/howtos/module/2015-05-09-how-to-override-modules.md
> +Please note that this article may be outdated and could potentially include inaccurate information. We recommend checking the latest documentation regarding [how to override modules](https://devdocs.
```suggestion
Please note that this article refers to very old versions of PrestaShop. Check out the documentation to learn [how to override modules](https://devdocs.prestashop-project.org/8/modules/concepts/overrides/#override-a-module).
```

2023-09-19 11:38 UTC, eternoendless commented on content/howtos/translation/2017-04-21-how-to-translate-your-theme.md
> +The translation system in PrestaShop evolved since 2017. Make sure to read the latest documentation on how to use translations in PrestaShop [for modules](https://devdocs.prestashop-project.org/8/mod
```suggestion
PrestaShop's translation system has evolved since this article was originally published in 2017. Make sure to read the latest documentation on how to use translations in PrestaShop [for modules](https://devdocs.prestashop-project.org/8/modules/creation/module-translation/), and [for themes](https://devdocs.prestashop-project.org/8/themes/reference/theme-translation/).
```

2023-09-19 11:38 UTC, eternoendless commented on content/howtos/translation/2017-04-21-how-to-translate-your-theme.md
> +{{% notice type="warning" title="Translations in PrestaShop" icon="megpahone" %}}
```suggestion
{{% notice type="warning" title="This article is outdated" icon="megaphone" %}}
```

2023-09-19 11:38 UTC, eternoendless commented on content/news/posts/2015/icon-pack-beta.md
> +{{% notice type="warning" title="No longer supported" icon="megpahone" %}}
```suggestion
{{% notice type="warning" title="No longer supported" icon="megaphone" %}}
```

2023-09-19 11:38 UTC, eternoendless commented on content/news/posts/2017/Child-Themes-Feature.md
> +{{% notice type="success" title="Documentation available!" icon="megpahone" %}}
```suggestion
{{% notice type="success" title="Documentation available!" icon="megaphone" %}}
```

2023-09-19 11:38 UTC, eternoendless commented on content/news/posts/2017/Child-Themes-Feature.md
> +If you want to use child-themes in PrestaShop, make sure to check the latest documentation on [how Parent/child theme feature works in PrestaShop](https://devdocs.prestashop-project.org/8/themes/refe
```suggestion
Make sure to check the latest documentation on [how the parent-child theme feature works in PrestaShop](https://devdocs.prestashop-project.org/8/themes/reference/template-inheritance/parent-child-feature/).
```

2023-09-19 11:38 UTC, eternoendless commented on content/news/posts/2017/prestashop-and-docker.md
> +If you want to read more about Docker in PrestaShop, make sure to check the latest documentation on [how to install and use PrestaShop with docker](https://devdocs.prestashop-project.org/8/basics/ins
```suggestion
{{% notice type="success" title="Documentation available!" icon="megaphone" %}}
If you want to learn more about Docker in PrestaShop, make sure to check the latest documentation on [how to install and use PrestaShop with docker](https://devdocs.prestashop-project.org/8/basics/installation/environments/docker/).
```

2023-09-19 11:38 UTC, eternoendless commented on content/news/posts/2019/announcing-end-of-support-for-obsolete-php-versions.md
> +You can check the current PHP compatibility of PrestaShop on [our documentation](https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/#php-requirements). For PrestaShop 1.
```suggestion
{{% notice type="success" title="Current PHP compatibility in PrestaShop" icon="megpahone" %}}
Check the documentation for PHP compatibility on [PrestaShop 8's system requirements](https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/#php-requirements) and [PrestaShop 1.7's system requirements](https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements/#php-requirements).
```

2023-09-19 11:38 UTC, eternoendless commented on content/news/posts/2022/new-theme-announce.md
> + It's been decided that Hummingbird will be the default theme for PrestaShop 9. You can take an active part in developing this new theme by [joining the discussion on Slack](https://www.prestashop-pr
```suggestion
 It has been decided that Hummingbird will be the default theme for PrestaShop 9. You can take an active part in developing this new theme by [joining the discussion on Slack](https://www.prestashop-project.org/slack/), testing the theme, and submitting improvements. Make sure to check out the [theme's repository on GitHub](https://github.com/PrestaShop/hummingbird).
```

2023-09-19 14:14 UTC, eternoendless approved these changes

2023-09-19 14:15 UTC, merged

2023-09-19 14:15 UTC, eternoendless commented
Thank you @kpodemski