Create do-you-speak-prestashop-august-2023.md
PrestaShop/prestashop.github.io pull request #1249
Opened 2023-09-13 15:10 UTC by l-delin

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Please be specific when describing the PR. What did you add, why did you submit it?
| Fixed ticket? | Fixes #{issue number here} if there is a related issue

2023-09-15 09:22 UTC, l-delin commented
Hello! My last DYSP is out 🗞
Could we get it published by Monday? @kpodemski @coffrep 🙂

ping @Julievrz

2023-09-15 10:36 UTC, coffrep requested changes
Hi @l-delin a great Build article by a great person. Thanks so much for your contributions! And for the handover to two great people also @Julievrz @axelvrsc. 
I've put the date to Monday if that is okay on the article (18th)? Let me know.

2023-09-15 10:36 UTC, coffrep commented on content/news/translation/2023/do-you-speak-prestashop-august-2023.md
> +date: 2023-09-17
```suggestion
date: 2023-09-18
```

2023-09-15 10:36 UTC, coffrep commented on content/news/translation/2023/do-you-speak-prestashop-august-2023.md
> +In it, you'll find everything about Crowdin & documentation translations, as well as the project's Terms of Use along with a few useful resources, including the PrestaShop glossary.
```suggestion
In it, you'll find everything about Crowdin and documentation translations, as well as the project's Terms of Use along with a few useful resources, including the PrestaShop glossary.
```

2023-09-15 11:25 UTC, l-delin commented
Hello @coffrep, seems good to me, thanks!

2023-09-18 07:47 UTC, Julievrz commented
@kpodemski Can we publish the article today, please? Thank you in advance for your help. 🤗

2023-09-18 08:21 UTC, coffrep approved these changes

2023-09-18 08:39 UTC, eternoendless commented
Thank you @l-delin

2023-09-18 08:39 UTC, merged