Update on Hummingbird situation
PrestaShop/prestashop.github.io pull request #1287
Opened 2024-04-12 08:37 UTC by kpodemski

2024-04-12 11:01 UTC, SharakPL approved these changes

2024-04-12 12:24 UTC, PrestaEdit requested changes
As it's an edit, I will appreciate that we leave the first content and just add the newest notice, there.

2024-04-12 15:35 UTC, matthieu-rolland approved these changes

2024-04-12 15:36 UTC, matthieu-rolland commented
> As it's an edit, I will appreciate that we leave the first content and just add the newest notice, there.

I think `While we would love to see Hummingbird in PrestaShop 9` reminds the reader that's that indeed what we want, or you want to make it more obvious that there is potentially a "change of plan" ?

2024-04-15 08:21 UTC, PrestaEdit commented
More obious, and I'd like to get the updated infos in addition of previous read, as an update and not a replacement, when I read a blog post from past, on my side.

2024-04-18 18:21 UTC, kpodemski commented
@PrestaEdit I edited the text, I hope we met halfway to clarify the message. The main point is to state the current situation.

2024-04-18 18:21 UTC, kpodemski commented
cc @matks @MatShir

2024-04-19 07:19 UTC, PrestaEdit commented
> @PrestaEdit I edited the text, I hope we met halfway to clarify the message. The main point is to state the current situation.

Thanks @kpodemski ! I appreciate the change, and approve it ! :)

2024-04-19 07:19 UTC, PrestaEdit approved these changes

2024-04-21 20:04 UTC, matks approved these changes
Good for me, let's publish tomorrow. Also added a little fix

2024-04-21 20:04 UTC, matks commented on content/news/posts/2022/new-theme-announce.md
> +{{% notice type="warning" title="April 2024: Hummingbird situation" icon="megpahone" %}}
```suggestion
{{% notice type="warning" title="April 2024: Hummingbird situation" icon="megaphone" %}}
```

2024-05-08 11:46 UTC, merged