Add blog post for back office rebranding
PrestaShop/prestashop.github.io pull request #1305
Opened 2024-08-26 12:51 UTC by tblivet

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Add blog post to introduce back office rebranding in PrestaShop v9
| Fixed ticket? | 

![post_preview](https://github.com/user-attachments/assets/feac5af5-f4ce-4d74-b0a6-e0c72ce404bf)

2024-08-26 12:51 UTC, ps-jarvis commented
<!-- PR_WELCOME -->
Hello @tblivet!

This is your first pull request on [prestashop.github.io](https://github.com/PrestaShop/prestashop.github.io/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

2024-09-02 12:33 UTC, kpodemski commented on content/news/posts/2024/prestashop-bo-rebrand.md
> +subtitle: "Rebranded Back Office Themes Now Available in PrestaShop v9"
```suggestion
subtitle: "Rebranded Back Office Themes Available in PrestaShop 9"
```

2024-09-02 12:42 UTC, kpodemski requested changes
Great job, @tblivet !

I'm adding some suggestions to it, and we can publish it tomorrow.

2024-09-02 12:42 UTC, kpodemski commented on content/news/posts/2024/prestashop-bo-rebrand.md
> +subtitle: "Rebranded Back Office Themes Now Available in PrestaShop v9"
```suggestion
subtitle: "Rebranded Back Office Themes Available in PrestaShop 9"
```

2024-09-02 12:42 UTC, kpodemski commented on content/news/posts/2024/prestashop-bo-rebrand.md
> +By the end of 2023, PrestaShop unveiled a new brand identity to strengthen its position, enhance credibility, and build trust. The PrestaShop back office is one of the last assets to receive this reb
```suggestion
By the end of 2023, PrestaShop unveiled a new brand identity to strengthen its position, enhance credibility, and build trust. [We already announced]({{< relref "/news/posts/2023/new-project-branding" >}}) the new branding for the project, and the PrestaShop back office is one of the last assets to follow this change. The release of PrestaShop 9 provided the perfect opportunity for this update. The rebranding involved significant changes to the PrestaShop back office, focusing on its two themes.
```

2024-09-02 12:42 UTC, kpodemski commented on content/news/posts/2024/prestashop-bo-rebrand.md
> +## Back Office Rebrand
```suggestion
## Back office rebranding
```

2024-09-02 12:42 UTC, kpodemski commented on content/news/posts/2024/prestashop-bo-rebrand.md
> +### Anatomy of the PrestaShop Back Office
```suggestion
### Anatomy of the PrestaShop back office
```

2024-09-02 12:42 UTC, kpodemski commented on content/news/posts/2024/prestashop-bo-rebrand.md
> +Updating both themes was essential to provide a consistent user experience throughout the back office. This harmonization effort focused on integrating CSS variables from the UI Kit, offering a centr
```suggestion
Updating both themes was essential to providing a consistent user experience throughout the back office. This harmonization effort focused on integrating CSS variables from the UI Kit, offering a centralized method to define design elements like colors, backgrounds, and shadows. The `_root.scss` file serves as a single source of truth for these variables, enabling efficient application style across both themes.
```

2024-09-02 12:42 UTC, kpodemski commented on content/news/posts/2024/prestashop-bo-rebrand.md
> +## Developer Tool for the Default Theme
```suggestion
## Developer tool for the default theme
```

2024-09-02 12:42 UTC, kpodemski commented on content/news/posts/2024/prestashop-bo-rebrand.md
> +### Why Use CSS Variables?
```suggestion
### Why CSS Variables?
```

2024-09-02 12:42 UTC, kpodemski commented on content/news/posts/2024/prestashop-bo-rebrand.md
> +tags: [ "9.0", Design ]
```suggestion
tags: [ "9.0", design, ux ]
```

2024-09-16 08:38 UTC, tblivet commented
Hello @kpodemski, I have just added your suggestions. Everything should be good now 👍

2024-09-16 10:15 UTC, coffrep approved these changes
Hi @tblivet, great piece of content, very well written. I've just added two minor edits, of course we should change the date to when this is posted. All good for me, thanks so much for this great Build post! Approved with edits on my end.

2024-09-16 10:15 UTC, coffrep commented on content/news/posts/2024/prestashop-bo-rebrand.md
> +subtitle: "Rebranded Back Office Themes Available in PrestaShop 9"
```suggestion
subtitle: "PrestaShop 9 Embarks The Newly Rebranded Back Office Themes"
```

2024-09-16 10:15 UTC, coffrep commented on content/news/posts/2024/prestashop-bo-rebrand.md
> +date:   2024-08-26
```suggestion
date:   2024-09-17
```

2024-09-17 05:35 UTC, kpodemski approved these changes

2024-09-17 05:42 UTC, merged

2024-09-17 05:43 UTC, kpodemski commented
thank you @tblivet @coffrep :)