Introducing PrestonBot article
PrestaShop/prestashop.github.io pull request #180
Opened 2016-09-14 16:29 UTC by mickaelandrieu

2016-09-21 12:28 UTC, xBorderie commented on news/_posts/2016-09-14-introducing-prestonbot.md
> +Some of you may have noticed that since weeks, we have welcome a new team member in the core team: Preston!
> Some of you may have noticed that a weeks ago, we have a new team member in the core team: Preston!

2016-09-21 12:28 UTC, xBorderie commented on news/_posts/2016-09-14-introducing-prestonbot.md
> +PrestonBot aims to both help maintainers and contributors of PrestaShop, let's see together what he's already  able to do and what you may expect from him in the future.
> PrestonBot aims to help both maintainers and contributors of PrestaShop. Let's see together what he's already  able to do and what you may expect from him in the future.

2016-09-21 12:29 UTC, xBorderie commented on news/_posts/2016-09-14-introducing-prestonbot.md
> +We are improving continuously the way we work with GitHub, adding a new mandatory Pull Request template:
> We are continuously improving the way we work with GitHub, for instance we recently added a new mandatory pull request template:

2016-09-21 12:30 UTC, xBorderie commented on news/_posts/2016-09-14-introducing-prestonbot.md
> +Questions | Why do we need it ?
> Why do we need it?

2016-09-21 12:31 UTC, xBorderie commented on news/_posts/2016-09-14-introducing-prestonbot.md
> +Branch    | A simple and stupid check to ensure the contribution realy concerns the branch used for the contribution.
> A simple check to ensure the contribution really concerns the branch it was submitted on.

2016-09-21 12:35 UTC, xBorderie commented on news/_posts/2016-09-14-introducing-prestonbot.md
> +Type | Is it a bug fix, an improvement or a new feature ? Bug fixes are often privileged, and new features are refused in `1.6.x` branch.
> in the `1.6.x` branch.

2016-09-21 12:37 UTC, xBorderie commented on news/_posts/2016-09-14-introducing-prestonbot.md
> +Category | In case of regression, prefixing commits help us figure out which update of codebase is responsible for. Also, this will help us to generate changelogs.
>  In case of a regression, prefixing commit names helps us figure out which code change is responsible for the issue.

2016-09-21 12:38 UTC, xBorderie commented on news/_posts/2016-09-14-introducing-prestonbot.md
> +If you complete the pull request template, PrestonBot is already able to make some "pre-validation" passes on new contributions. For instance, let's say you forgot to add a meaning full description t
> meaningful description

2016-09-21 12:38 UTC, xBorderie commented on news/_posts/2016-09-14-introducing-prestonbot.md
> + Nice, isn't it ? Every time you update the pull request, PrestonBot will check again and stop annoying you when it's valid!
> Nice, isn't it?

2016-09-21 12:39 UTC, xBorderie commented on news/_posts/2016-09-14-introducing-prestonbot.md
> +PrestaShop is a project done by a lot of different people: developers of course but also translators, testers, product managers and so on.
> PrestaShop is a project which involves a lot of...

2016-09-21 12:40 UTC, xBorderie commented on news/_posts/2016-09-14-introducing-prestonbot.md
> +Before, GitHub - the hosting platform of PrestaShop project - have a very limited system to allow people to interact with PrestaShop.
> The PrestaShop project is hosted on GitHub. Until recently, the tools it had to allow people to interact with the PrestaShop team were very limited

2016-09-21 12:41 UTC, xBorderie commented on news/_posts/2016-09-14-introducing-prestonbot.md
> +Basicaly, if you wanted to allow someone to labelize an issue, you have to give him mostly all the rights on the project.
> ..., you had to give

2016-09-21 12:43 UTC, xBorderie commented on news/_posts/2016-09-14-introducing-prestonbot.md
> +Since the recent [GitHub announcements](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features), giving rights to any contributor is now really easy. Using
> without allowing any possibility

2016-09-21 12:44 UTC, xBorderie commented on news/_posts/2016-09-14-introducing-prestonbot.md
> +Our own - "non developer" - teams are already enjoying the new GitHub system and we will welcome community members in PrestaShop organization very soon as *Code reviewers* !
> Our own - "non developer" - team members are...

2016-09-21 12:45 UTC, xBorderie commented on news/_posts/2016-09-14-introducing-prestonbot.md
> +Our own - "non developer" - teams are already enjoying the new GitHub system and we will welcome community members in PrestaShop organization very soon as *Code reviewers* !
Y'a-t-il d'autres chose que Preston puisse faire ?
Quels sont les plans pour son avenir, les prochaines fonctionnalités ?

2016-09-21 15:31 UTC, xBorderie requested changes
DO IT.

2016-09-22 10:03 UTC, AlexEven commented on news/_posts/2016-09-14-introducing-prestonbot.md
> +Some of you may have noticed that since weeks, we have welcome a new team member in the core team: Preston!
a weeks?
Some of you may have noticed that a few weeks ago we welcomed a new member in the core team: Preston!

2016-09-22 10:05 UTC, AlexEven commented on news/_posts/2016-09-14-introducing-prestonbot.md
> +Questions | Why do we need it ?
all the details / all the information (no "s" in English ;) )

2016-09-22 10:10 UTC, AlexEven commented on news/_posts/2016-09-14-introducing-prestonbot.md
> +If you complete the pull request template, PrestonBot is already able to make some "pre-validation" passes on new contributions. For instance, let's say you forgot to add a meaningful description des
description x 2

2016-09-22 10:12 UTC, AlexEven commented on news/_posts/2016-09-14-introducing-prestonbot.md
> +Our own - "non developer" - team members are already enjoying the new GitHub system and we will welcome community members in PrestaShop organization very soon as *Code reviewers* !
*Code reviewers*!

2016-09-22 11:08 UTC, mickaelandrieu commented on news/_posts/2016-09-14-introducing-prestonbot.md
> +If you complete the pull request template, PrestonBot is already able to make some "pre-validation" passes on new contributions. For instance, let's say you forgot to add a meaningful description des
oups :(

2016-09-22 11:10 UTC, mickaelandrieu commented
@AlexEven thanks for review, comments addressed :)
@xBorderie comments addressed too

2016-09-23 13:29 UTC, merged

2016-09-23 13:30 UTC, mickaelandrieu commented
Let's publish it on moday this way, if anyone want to improve something, feel free to do it !