1.7.4 is ready for translation
PrestaShop/prestashop.github.io pull request #408
Opened 2018-06-20 10:10 UTC by LouiseBonnard

2018-06-20 10:41 UTC, ttoine requested changes
--- we decided not to close the previous branches anymore in order to avoid ---
il manque quelque chose, on dirait

2018-06-22 09:10 UTC, merged

2018-06-22 09:16 UTC, eternoendless commented on news/_posts/translation/2018-06-22-174-translations.md
> +However, we later realized that keeping only the latest minor version of PrestaShop active on Crowdin was not so good an idea. Indeed, --- we decided not to close the previous branches anymore in ord
I think this whole section can be deleted as this hasn't been addressed yet

2018-06-22 09:16 UTC, eternoendless commented on news/_posts/translation/2018-06-22-174-translations.md
> +And that know, let’s explain why we had to regenerate the 1.7.4 catalog many times. We are very sorry for the relentless translators who have had to do the job twice, be sure the problem is solved. W
And that said, you may have noticed that we had to regenerate the 1.7.4 catalog many times. We are very sorry for the relentless translators who have had to do the job twice, be rest assured, the problem is now solved. What happened is that we first had a bug in the library we use to extract strings (it wasn't able to extract some of them), then we realized we had deleted some strings we thought we didn't need but actually we did… so we put them back in the code and everything went back in order. Phew!

2018-06-22 09:16 UTC, eternoendless commented on news/_posts/translation/2018-06-22-174-translations.md
> +Of course, as the context is not fully available because PrestaShop 1.7.4 is not out for now (but will soon be), some of these strings may appear a bit unclear. But ask if you need explanations, we w
They can actually check it out if they download the beta

2018-06-22 09:16 UTC, eternoendless commented on news/_posts/translation/2018-06-22-174-translations.md
> +All this to say new strings have been added to our projects available in Crowdin. Modifications are more than allowed, it will help us having [PrestaShop 1.7.4](https://crowdin.com/project/prestashop
> Modifications are more than allowed

"Modifications are more than _welcome_"

> as much ready as possible for all!

There's a problem there, I don't think you can say "much ready" (unless you're doge: much ready, such finished).

I believe "As ready as possible" would be fine 🙂