1.7.6.2 Release Note
PrestaShop/prestashop.github.io pull request #655
Opened 2020-03-04 16:35 UTC by MatShir

2020-03-04 16:39 UTC, matks commented on news/_posts/releases/2020-03-04-prestashop-1-7-6-4-maintenance-release.md
> +Reminder:  the 1-Click Upgrade module’s latest version is v[VERSION], don’t forget to upgrade it.
Dont forget adding version

2020-03-04 17:30 UTC, matks commented on news/_posts/releases/2020-03-04-prestashop-1-7-6-4-maintenance-release.md
> +image: /assets/images/2019/11/meta-1762.png
1762 or 1764 ?

2020-03-04 17:35 UTC, ttoine requested changes

2020-03-04 17:35 UTC, ttoine commented on news/_posts/releases/2020-03-04-prestashop-1-7-6-4-maintenance-release.md
> +date:   2019-11-28 16:00:00
```suggestion
date:   2020-03-04 10:00:00
```

2020-03-04 17:35 UTC, ttoine commented on news/_posts/releases/2020-03-04-prestashop-1-7-6-4-maintenance-release.md
> +Read the [full changelog here](https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.6.4).
```suggestion
Read the [full changelog here](https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.6.4).


```

2020-03-05 09:45 UTC, matthieu-rolland approved these changes

2020-03-05 10:29 UTC, colinegin requested changes

2020-03-05 10:29 UTC, colinegin commented on news/_posts/releases/2020-03-04-prestashop-1-7-6-4-maintenance-release.md
> +After a few months dedicated to fixing a security issue and all regressions found on the previous 1.7.6 versions, PrestaShop 1.7.6.4 is finally available!
After a few weeks

2020-03-05 10:29 UTC, colinegin commented on news/_posts/releases/2020-03-04-prestashop-1-7-6-4-maintenance-release.md
> +This maintenance release fixes 9 issues reported on the versions between 1.7.6.0 to the 1.7.6.3.
reported from versions 1.7.6.0 to 1.7.6.3.

2020-03-05 10:29 UTC, colinegin commented on news/_posts/releases/2020-03-04-prestashop-1-7-6-4-maintenance-release.md
> +Below are listed some of the main regression issues we fixed in this version :
Below are listed all regression issues

2020-03-05 10:29 UTC, colinegin commented on news/_posts/releases/2020-03-04-prestashop-1-7-6-4-maintenance-release.md
> +* Failed load the product_page.css and translations.css files ([#17584](https://github.com/PrestaShop/PrestaShop/issues/17584))
Failure on loading

2020-03-05 10:29 UTC, colinegin commented on news/_posts/releases/2020-03-04-prestashop-1-7-6-4-maintenance-release.md
> +* Couldn’t view a category if all subcategories were disabled ([#17379](https://github.com/PrestaShop/PrestaShop/issues/17379))
View on category not possible when all subcategories were disabled

2020-03-05 10:29 UTC, colinegin commented on news/_posts/releases/2020-03-04-prestashop-1-7-6-4-maintenance-release.md
> +* Some products combination wasn’t displayed depending on the stock and the product configuration ([#17345](https://github.com/PrestaShop/PrestaShop/issues/17345))
Some product combinations were not displayed on particular stock and product configurations

2020-03-05 10:29 UTC, colinegin commented on news/_posts/releases/2020-03-04-prestashop-1-7-6-4-maintenance-release.md
> +* A reduction error occurred on the invoice when applying specific cart rule to an order
An error on the discount occurred on the invoice when applying a specific cart rule to an order

2020-03-05 10:29 UTC, colinegin commented on news/_posts/releases/2020-03-04-prestashop-1-7-6-4-maintenance-release.md
> +Below are the security information we added in this version:
Find below detailed information about the security fix provided in this version:

2020-03-05 10:29 UTC, colinegin commented on news/_posts/releases/2020-03-04-prestashop-1-7-6-4-maintenance-release.md
> +* Email’s subject can have special character again ([#16847](https://github.com/PrestaShop/PrestaShop/issues/16847))
Display issue on emails' subject with special characters

2020-03-05 10:37 UTC, MatShir commented
Final review @ttoine before merging. We are ready!

2020-03-05 10:55 UTC, merged