Article about TypeScript adoption
PrestaShop/prestashop.github.io pull request #877
Opened 2021-04-06 16:19 UTC by NeOMakinG

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | We need to inform the community about our adoption of TypeScript

2021-04-09 12:36 UTC, matthieu-rolland commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +PHP recent works are also strictly typed. This is mainly why we wants to strictly type the JavaScript side!
```suggestion
PHP recent works are also strictly typed. This is mainly why we want to strictly type the JavaScript side! 
```

2021-04-09 12:37 UTC, matthieu-rolland commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +We already seen some benefits about strictly typing PHP, it provide a robust codebase and avoid a lot of bugs by spotting these really early. This will provide us a safe development way and increase
```suggestion
We've already seen some benefits about strictly typing PHP, it provide a robust codebase and avoid a lot of bugs by spotting these really early. This will provide us a safe development way and increase our confidence about what we're still building.
```

or `we already saw`

2021-04-09 12:39 UTC, matthieu-rolland commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +On good reason is that every big JavaScript projects switched their codebase from Flow to TypeScript recently (Vue 3, Jest for example), this means that a lot of external developers are building proj
```suggestion
One good reason is that every big JavaScript projects switched their codebase from Flow to TypeScript recently (Vue 3, Jest for example), this means that a lot of external developers are building projects using this library, this way we ensure that JavaScript contributors won't be lost when reading our work.
```

2021-04-09 12:40 UTC, matthieu-rolland commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +There are a lot of more reasons:
```suggestion
There are a lot more reasons:
```

2021-04-09 12:41 UTC, matthieu-rolland commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +PHP recent works are also strictly typed. This is mainly why we wants to strictly type the JavaScript side!
`PHP recent works are also strictly typed` => are you talking about our code or PHP in general?

2021-04-09 12:44 UTC, NeOMakinG commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +PHP recent works are also strictly typed. This is mainly why we wants to strictly type the JavaScript side!
Our code

2021-04-09 12:45 UTC, NeOMakinG commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +On good reason is that every big JavaScript projects switched their codebase from Flow to TypeScript recently (Vue 3, Jest for example), this means that a lot of external developers are building proj
Damn :p

2021-04-09 12:45 UTC, matthieu-rolland commented
Maybe one good argument could be that in some cases, typescript interfaces could perfectly reflect interfaces we have in the backend,  giving more coherence to the backend/frontend relationship.

2021-04-12 08:39 UTC, Progi1984 commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +Recently, the PrestaShop core team decided to use TypeScript (TS) on the project. [We recently submited an Architecture Decision Records (ADR)](https://github.com/PrestaShop/ADR/pull/19) and a [Proof
It's not merged :p so it's in discussion

2021-04-12 08:42 UTC, NeOMakinG commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +Recently, the PrestaShop core team decided to use TypeScript (TS) on the project. [We recently submited an Architecture Decision Records (ADR)](https://github.com/PrestaShop/ADR/pull/19) and a [Proof
an ADR and a POC is all about discussion isn't it ? :p

2021-04-14 08:57 UTC, Progi1984 commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +Recently, the PrestaShop core team decided to use TypeScript (TS) on the project. [We recently submited an Architecture Decision Records (ADR)](https://github.com/PrestaShop/ADR/pull/19) and a [Proof
```suggestion
Recently, the PrestaShop core team decided to use TypeScript (TS) on the project. [We recently submitted an Architecture Decision Records (ADR)](https://github.com/PrestaShop/ADR/pull/19) and a [Proof of Concept (POC)](https://github.com/PrestaShop/PrestaShop/pull/23221) in order to use TypeScript on every development we do.
```

2021-04-14 09:14 UTC, Progi1984 commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +PrestaShop recently increased his code quality by adding a lot of tools:
```suggestion
PrestaShop recently increased its code quality by adding a lot of tools:
```

2021-04-14 09:19 UTC, Progi1984 commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +One good reason is that every big JavaScript projects switched their codebase from Flow to TypeScript recently (Vue 3, Jest for example), this means that a lot of external developers are building pro
Explain what is Flow.

2021-04-14 09:20 UTC, Progi1984 commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +- It's open source and powered by a big company (Microsoft)
```suggestion
- TypeScript has better performance.
- It has a larger community (TypeScript is listed on [state of JS](https://2020.stateofjs.com/en-US/technologies/)).
- It's open source and powered by a big company (Microsoft).
```

2021-04-14 09:20 UTC, Progi1984 commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +For the moment, every new JS files will be written using TypeScript, with strongly typed components. We also need to refacto every sensible components such as grids and important pages scripts, in or
```suggestion
For the moment, every new JS files will be written using TypeScript, with strongly typed components. We also need to refactor every sensible components such as grids and important pages scripts, in order to be able to catch as much bugs as we can and provide a maintainable codebase.
```

2021-04-14 09:20 UTC, Progi1984 commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +We're focusing the Back-Office, Classic theme won't be refacto using TS for the moment, because it will lead to a lot of breaking changes, meaning that every themes using Classic may be broken. This
```suggestion
We're focusing the Back-Office, Classic theme won't be refactor using TS for the moment, because it will lead to a lot of breaking changes, meaning that every themes using Classic may be broken. This is not something we wants.
```

2021-04-14 09:20 UTC, Progi1984 reviewed
Some feedbacks

2021-04-14 15:15 UTC, NeOMakinG commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +One good reason is that every big JavaScript projects switched their codebase from Flow to TypeScript recently (Vue 3, Jest for example), this means that a lot of external developers are building pro
Explained in the title

2021-04-15 09:50 UTC, Progi1984 approved these changes

2021-04-20 08:10 UTC, matthieu-rolland commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +
maybe we could emphasize the benefits of better static analysis:

- better autocomplete and intelligence in code editors 
- which implies earlier bug detection while coding
- potentially we could have a better CI for our ts code with things like typescript-eslint

2021-04-20 10:45 UTC, NeOMakinG commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +
I think it's a good idea

2021-04-21 07:45 UTC, Progi1984 approved these changes

2021-04-22 10:39 UTC, eternoendless requested changes

2021-04-22 10:39 UTC, eternoendless commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +PHP recent works are also strictly typed. This is mainly why we want to strictly type the JavaScript side!
```suggestion
In addition, we have started enforcing [strict types](https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.strict) in all new PHP classes since PrestaShop 1.7.7, which allows us to catch a lot of problems before they become bugs. This is why our next step is to bring strict types to JavaScript as well!
```

2021-04-22 10:39 UTC, eternoendless commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +We've already seen some benefits about strictly typing PHP, it provides a robust codebase and avoids a lot of bugs by spotting these really early while coding. This will provide us a safe development
```suggestion
We have already seen the benefits of strictly typing in PHP: it has increased the codebase's robustness by making type juggling bugs evident while coding and in CI. A type-safe environment reduces the chances of errors and enhances developers' confidence in what they are building.
```

2021-04-22 10:39 UTC, eternoendless commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +It also makes the code way more self-expressive, which means that our codebase will be more friendly to new developers and contributors.
```suggestion
TypeScript also allows more expressive code, which will help new developers and contributors.
```

2021-04-22 10:39 UTC, eternoendless commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +As our codebase is mainly using OOP, TypeScript will provide a lot of concepts to empower our pattern that JavaScript doesn't provide for the moment such as private methods for example...
```suggestion
In addition to strict types, TypeScript also provides a lot of useful language features that JavaScript doesn't, such as private methods, interfaces, generics, and more.
```

2021-04-22 10:39 UTC, eternoendless commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +One good reason is that every big JavaScript projects switched its codebase from Flow to TypeScript recently (Vue 3, Jest for example), this means that a lot of external developers are building proje
```suggestion
One good reason is that many big JavaScript projects like Vue and Jest have recently switched their codebases from Flow to TypeScript – This means that a lot of developers are building their projects using TypeScript. Hence, we think that using TypeScript will maximize the chances that developers won't be lost when reading PrestaShop's code.
```

2021-04-22 10:39 UTC, eternoendless commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +There are a lot more reasons:
```suggestion
There are many more reasons:
```

2021-04-22 10:39 UTC, eternoendless commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +- It's open-source and powered by a big company (Microsoft).
```suggestion
- It's open-source and backed by a big company (Microsoft).
```

2021-04-22 10:39 UTC, eternoendless commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +- It's natively compatible with most editors making the autocomplete powerfull and bug discovery way easier.
```suggestion
- Most IDEs support it out of the box, providing autocomplete and inspections.
```

2021-04-22 10:39 UTC, eternoendless commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +## What's the future?
```suggestion
## What's next?
```

2021-04-22 10:39 UTC, eternoendless commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +For the moment, every new JS file will be written using TypeScript, with strongly typed components. We also need to refactor every sensible component such as grids and important page scripts, in orde
```suggestion
For the moment, only new components will be written using TypeScript. In time, we will progressively refactor important components such as grids and page scripts, to benefit from the enhanced stability and maintainability provided by TypeScript's strong-typing features.
```

2021-04-22 10:39 UTC, eternoendless commented on news/_posts/2021-04-06-we-decided-to-use-typescript.md
> +
I think we can leave this part out, to finish with a good note. This article is about what we will do, not what we won't do.
```suggestion
```

2021-04-26 10:06 UTC, Progi1984 commented on news/_posts/2021-04-22-we-decided-to-use-typescript.md
> +Following a recent [Architecture Decision Records (ADR) submission](https://github.com/PrestaShop/ADR/pull/19) and a [Proof of Concept (POC)](https://github.com/PrestaShop/PrestaShop/pull/23221), the
```suggestion
Following a recent [Architecture Decision Records (ADR) submission](https://github.com/PrestaShop/ADR/pull/19) and a [Proof of Concept (POC)](https://github.com/PrestaShop/PrestaShop/pull/23221), the Core Maintainers team has decided to introduce [TypeScript](https://www.typescriptlang.org/) (TS) on the project.
```

2021-04-26 10:07 UTC, Progi1984 approved these changes

2021-05-18 08:40 UTC, matthieu-rolland approved these changes

2021-05-28 13:58 UTC, eternoendless commented on news/_posts/2021-04-22-we-decided-to-use-typescript.md
> +During the last few years, the PrestaShop Project has been increasinlgy raising the code quality bar. To help maintainers ensure that quality keeps increasing, a number of automatic quality verificat
```suggestion
During the last few years, the PrestaShop Project has been increasingly raising the code quality bar. To help maintainers ensure that quality keeps increasing, a number of automatic quality verification tools have been added to the CI pipeline:
```

2021-05-28 13:58 UTC, eternoendless commented on news/_posts/2021-04-22-we-decided-to-use-typescript.md
> +## Why TypeScript and not another typing library such as Flow?
```suggestion
## Why TypeScript and not another strict type library such as Flow?
```

2021-05-28 14:02 UTC, eternoendless approved these changes

2021-05-28 14:02 UTC, eternoendless commented
LGTM

Thank you @NeOMakinG

2021-05-28 14:15 UTC, merged